#!/usr/bin/env python3

if __name__ == '__main__':
    import os, sys
    sys.path.append(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src')
    )
    import cubeserv
    cubeserv.Application(sys.argv).run()

